### ISSUE TITLE
foreground colors change after sourcing  .vimrc file

### ISSUE THREAD

**Issue by ducaale** [morhetz/gruvbox#166]
when `.vimrc` is sourced manually the colors change

before :
![before](https://cloud.githubusercontent.com/assets/16341131/24599657/dcb99498-1859-11e7-80f2-2b2e660ce38a.PNG)

after running `so%` :
![after](https://cloud.githubusercontent.com/assets/16341131/24599683/fbf0f9d2-1859-11e7-87e5-9b4ca50f776f.PNG)

I am running  Neovim 0.2-dev with termguicolors enabled on Ubuntu 14.04 through WSL/Windows 10, using st suckless terminal as terminal.

**Comment by sus007** [comment]
@ducaale Do you mind sharing your configuration for Vim ? I too have the same OS setup as yours. But, when I installed this theme, my Vim got messed up. The colors started bleeding, fading out when I scroll. 🙁

**Comment by ducaale** [comment]
here it is https://github.com/ducaale/dotfiles/blob/master/neovim/.config/nvim/init.vim
by the way I think this issue is now fixed after last windows update (fall creators update)

**Comment by sus007** [comment]
not really, the issue still persists for common Vim, and apparently for some Neovim users too. ➡ https://github.com/Microsoft/WSL/issues/2710
